sudo: required
language: go
services:
  - docker
script: DEV_REGISTRY="docker.io" make bootstrap build test-cover
tifications:
  slack:
    rooms:
      - drycc:xKmLlmJR4hfRAgVIOwdpAoC9#drycc
after_success:
  - bash <(curl -s https://codecov.io/bash)
