apiVersion: v1
kind: Secret
metadata:
  name: storage-creds
  labels:
    heritage: drycc
type: Opaque
data:
  {{- if eq .Values.global.storageLocation "on-cluster"}}
  lookup: {{ "path" | b64enc }}
  {{- $health := (printf "http://drycc-storage-minio.%s.svc.%s:8082/healthz" .Release.Namespace .Values.global.clusterDomain) }}
  health: {{ $health | b64enc }}
  {{- $endpoint := (printf "http://drycc-storage-minio.%s.svc.%s:9000" .Release.Namespace .Values.global.clusterDomain) }}
  endpoint: {{ $endpoint | b64enc }}
  builder-bucket: {{ "builder" | b64enc }}
  registry-bucket: {{ "registry" | b64enc }}
  {{- else }}
  lookup: {{ .Values.lookup | b64enc }}
  health: {{ if .Values.health | default "" | ne "" }}{{ .Values.health | b64enc }}{{ else }}{{ .Values.endpoint | b64enc }}{{ end }}
  endpoint: {{ .Values.endpoint | b64enc }}
  builder-bucket: {{ .Values.builderBucket | b64enc }}
  registry-bucket: {{ .Values.registryBucket | b64enc }}
  {{- end }}
  accesskey: {{ if .Values.accesskey | default "" | ne "" }}{{ .Values.accesskey | b64enc }}{{ else }}{{ randAlphaNum 32 | b64enc }}{{ end }}
  secretkey: {{ if .Values.secretkey | default "" | ne "" }}{{ .Values.secretkey | b64enc }}{{ else }}{{ randAlphaNum 32 | b64enc }}{{ end }}
