{{- if eq .Values.global.storageLocation "on-cluster" }}
apiVersion: v1
kind: Service
metadata:
  name: drycc-storage
  annotations:
    {{- with .Values.storage.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    heritage: drycc
spec:
  type: ClusterIP
  selector:
    app: drycc-storage
  ports:
    - name: s3
      port: 9000
{{- end }}
