name: minio
home: https://github.com/drycc/minio
version:  <Will be populated by the ci before publishing the chart>
description: Minio Object Storage in Kubernetes, used by Drycc Workflow.
maintainers:
  - name: Drycc Team
    email: engineering@drycc.com
