imageOrg: "drycc"
imagePullPolicy: "Always"
imageTag: "canary"
imageRegistry: "registry.drycc.cc"

# The following parameters are configured only when using an on-cluster Minio instance
nodeAffinityPreset:
  key: "drycc.cc/node"
  type: "soft"
  values:
  - "true"

podAffinityPreset:
  key: "security"
  type: ""
  values:
  - "drycc-security"

podAntiAffinityPreset:
  key: "app"
  type: "soft"
  values:
  - "drycc-minio"

# Minio zone count
zones: 1
# Device count of per replica
drives: 4
# Number of replicas per zone
replicas: 1

# Service
service:
  # Provide any additional service annotations
  annotations: {}

persistence:
  enabled: false
  accessMode: ReadWriteOnce
  size: 5Gi
  storageClass: ""
  volumeName: ""

global:
  storage: minio
