imageOrg: "drycc"
imagePullPolicy: "Always"
imageTag: "canary"
imageRegistry: "docker.io"
# Service
service:
  # Provide any additional service annotations
  annotations: {}
persistence:
  enabled: false
  accessMode: ReadWriteOnce
  size: 5Gi
  storageClass: ""
  volumeName: ""
global:
  storage: minio
