image_org: "drycc"
image_pull_policy: "Always"
image_tag: "canary"
image_registry: "docker.io"
persistence:
  enabled: false
  accessMode: ReadWriteOnce
  size: 5Gi
  storageClass: ""
  volumeName: ""
global:
  storage: minio
