apiVersion: v1
kind: Service
metadata:
  name: drycc-minio
  annotations:
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    heritage: drycc
spec:
  ports:
    - name: s3
      port: 9000
  selector:
    app: drycc-minio