apiVersion: apps/v1
kind: Deployment
metadata:
  name: drycc-minio
  labels:
    heritage: drycc
  annotations:
    component.drycc.cc/version: {{ .Values.image_tag }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: drycc-minio
  template:
    metadata:
      labels:
        app: drycc-minio
    spec:
      serviceAccount: drycc-minio
      containers:
        - name: drycc-minio
          image: {{.Values.image_registry}}/{{.Values.image_org}}/minio:{{.Values.image_tag}}
          imagePullPolicy: {{.Values.image_pull_policy}}
          env:
            - name: STORAGE
              value: "{{.Values.global.storage}}"
            - name: HEALTH_SERVER_PORT
              value: "8082"
          ports:
            - containerPort: 9000
            - containerPort: 8082
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8082
            initialDelaySeconds: 30
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8082
            initialDelaySeconds: 30
            timeoutSeconds: 1
          command:
            - boot
          args:
            {{- if eq .Values.global.storage "minio" }}
            - "server"
            - "/data"
            {{- else}}
            - "gateway"
            - "{{.Values.global.storage}}"
            {{- end}}
          volumeMounts:
            - name: objectstore-creds
              mountPath: /var/run/secrets/drycc/objectstore/creds
          {{- if .Values.persistence.enabled }}
            - name: minio-data
              mountPath: /data
          {{- end }}
      volumes:
        - name: objectstore-creds
          secret:
            secretName: objectstorage-keyfile
        {{- if .Values.persistence.enabled }}
        - name: minio-data
          persistentVolumeClaim:
            claimName: drycc-minio
        {{- end }}
