{{- if eq .Values.global.storage "minio" }}
apiVersion: v1
kind: Service
metadata:
  name: drycc-minio
  labels:
    heritage: drycc
spec:
  ports:
    - name: s3
      port: 9000
  selector:
    app: drycc-minio
{{- end }}
