name: storage
home: https://github.com/drycc/storage
apiVersion: v2
appVersion: 1.0.0
dependencies:
  - name: common
    repository: oci://registry.drycc.cc/charts
    version: ~1.1.2
description: Drycc Storage in Kubernetes, used by Drycc Workflow.
maintainers:
  - name: Drycc Team
    email: engineering@drycc.com
version:  v1.0.0
