imageOrg: "drycc"
imagePullPolicy: "Always"
imageTag: "canary"
imageRegistry: "registry.drycc.cc"

minio:
  # The following parameters are configured only when using an on-cluster storage instance
  nodeAffinityPreset:
    key: "drycc.cc/node"
    type: "soft"
    values:
    - "true"
  podAffinityPreset:
    key: "security"
    type: ""
    values:
    - "drycc-security"
  # Service
  service:
    # Provide any additional service annotations
    annotations: {}
  # The following parameters are configured only when using an on-cluster Storage instance
  podAntiAffinityPreset:
    key: "app"
    type: "soft"
    values:
    - "drycc-storage"
  # Storage zone count
  zones: 1
  # Device count of per replica
  drives: 4
  # Number of replicas per zone
  replicas: 1
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 5Gi
    storageClass: ""

meta:
  # pd
  pd:
    # Service
    service:
      # Provide any additional service annotations
      annotations: {}
    replicas: 1
    podAntiAffinityPreset:
      key: "app"
      type: "soft"
      values:
      - "drycc-storage-meta-pd"
    # persistence config
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 10Gi
      storageClass: ""

  # tikv
  tikv:
  # Service
    service:
      # Provide any additional service annotations
      annotations: {}
    replicas: 1
    podAntiAffinityPreset:
      key: "app"
      type: "soft"
      values:
      - "drycc-storage-meta-tikv"
  # persistence config
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 10Gi
      storageClass: ""

# drycc storage csi
csi:
  enabled: true
  daemonset:
    registrarImage: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.5.0
  statefulset:
    replicas: 1
    resizerImage: k8s.gcr.io/sig-storage/csi-resizer:v1.4.0
    attacherImage: k8s.gcr.io/sig-storage/csi-attacher:v3.4.0
    provisionerImage: k8s.gcr.io/sig-storage/csi-provisioner:v3.1.0
  provider: juicefs
  storageClass:
    # Specifies whether the storage class should be created
    create: true
    # Name
    name: drycc-storage
    # Volume reclaim policy
    reclaimPolicy: Delete
    # Annotations for the storage class
    # Example:
    # annotations:
    #   storageclass.kubernetes.io/is-default-class: "true"
    annotations: {}
    # storageClass parameters
    parameters:
      # Fuse mount options
      options: "--max-uploads=50 --writeback --cache-size=204800"

global:
  # A domain name consists of one or more parts.
  # Periods (.) are used to separate these parts.
  # Each part must be 1 to 63 characters in length and can contain lowercase letters, digits, and hyphens (-).
  # It must start and end with a lowercase letter or digit.
  clusterDomain: "cluster.local"

  storageLocation: "on-cluster"
