{{- if eq .Values.global.storageLocation "on-cluster" }}
{{- if .Values.csi.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: drycc-storage-csi
  labels:
    heritage: drycc
{{- end }}
{{- end }}
