{{- if eq .Values.global.storageLocation "on-cluster" }}
{{- if .Values.csi.enabled }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ printf "%s:drycc-storage-csi" .Release.Namespace | quote }}
subjects:
  - kind: ServiceAccount
    name: drycc-storage-csi
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ printf "%s:drycc-storage-csi" .Release.Namespace | quote }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
