{{- if eq .Values.global.storageLocation "on-cluster" }}
apiVersion: v1
kind: Service
metadata:
  name: drycc-storage-meta-pd
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "2379"
    prometheus.io/scrape: "true"
    {{- with .Values.meta.pd.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    heritage: drycc
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: drycc-storage-meta-pd
  ports:
    - name: advertise-client
      port: 2379
      targetPort: 2379
      protocol: TCP
    - name: advertise-peer
      port: 2380
      targetPort: 2380
      protocol: TCP
{{- end }}
